INTERFACE
SUBROUTINE RRTM_CMBGB15_GPU(lacc)
logical, intent (in) :: lacc
END SUBROUTINE RRTM_CMBGB15_GPU
END INTERFACE
INTERFACE
SUBROUTINE RRTM_CMBGB15_CPU
END SUBROUTINE RRTM_CMBGB15_CPU
END INTERFACE