INTERFACE
SUBROUTINE RRTM_CMBGB14_GPU(lacc)
logical, intent (in) :: lacc
END SUBROUTINE RRTM_CMBGB14_GPU
END INTERFACE
INTERFACE
SUBROUTINE RRTM_CMBGB14_CPU
END SUBROUTINE RRTM_CMBGB14_CPU
END INTERFACE