INTERFACE
SUBROUTINE RRTM_CMBGB12_GPU(lacc)
logical, intent (in) :: lacc
END SUBROUTINE RRTM_CMBGB12_GPU
END INTERFACE
INTERFACE
SUBROUTINE RRTM_CMBGB12_CPU
END SUBROUTINE RRTM_CMBGB12_CPU
END INTERFACE