INTERFACE
SUBROUTINE RRTM_CMBGB10_GPU(lacc)
logical, intent (in) :: lacc
END SUBROUTINE RRTM_CMBGB10_GPU
END INTERFACE
INTERFACE
SUBROUTINE RRTM_CMBGB10_CPU
END SUBROUTINE RRTM_CMBGB10_CPU
END INTERFACE