INTERFACE
SUBROUTINE RRTM_CMBGB13_GPU(lacc)
logical, intent (in) :: lacc
END SUBROUTINE RRTM_CMBGB13_GPU
END INTERFACE
INTERFACE
SUBROUTINE RRTM_CMBGB13_CPU
END SUBROUTINE RRTM_CMBGB13_CPU
END INTERFACE