INTERFACE
SUBROUTINE RRTM_CMBGB11_GPU(lacc)
logical, intent (in) :: lacc
END SUBROUTINE RRTM_CMBGB11_GPU
END INTERFACE
INTERFACE
SUBROUTINE RRTM_CMBGB11_CPU
END SUBROUTINE RRTM_CMBGB11_CPU
END INTERFACE