INTERFACE
SUBROUTINE RRTM_CMBGB16_GPU(lacc)
logical, intent (in) :: lacc
END SUBROUTINE RRTM_CMBGB16_GPU
END INTERFACE
INTERFACE
SUBROUTINE RRTM_CMBGB16_CPU
END SUBROUTINE RRTM_CMBGB16_CPU
END INTERFACE