INTERFACE
SUBROUTINE RRTM_INIT_140GP_GPU(DIRECTORY, lacc)
CHARACTER(LEN=*), INTENT(IN) :: DIRECTORY
logical, intent (in) :: lacc
END SUBROUTINE RRTM_INIT_140GP_GPU
END INTERFACE
INTERFACE
SUBROUTINE RRTM_INIT_140GP_CPU(DIRECTORY)
CHARACTER(LEN=*), INTENT(IN) :: DIRECTORY
END SUBROUTINE RRTM_INIT_140GP_CPU
END INTERFACE