interface
SUBROUTINE SATUR_GPU ( KIDIA , KFDIA , KLON , KTDIA , KLEV, LDPHYLIN, &
 & PAPRSF, PT , PQSAT , KFLAG, lacc)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KTDIA
LOGICAL ,INTENT(IN) :: LDPHYLIN
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRSF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQSAT(KLON,KLEV)
INTEGER(KIND=JPIM),INTENT(IN) :: KFLAG
logical, intent (in) :: lacc
END SUBROUTINE SATUR_GPU
end interface
interface
SUBROUTINE SATUR_CPU ( KIDIA , KFDIA , KLON , KTDIA , KLEV, LDPHYLIN, &
 & PAPRSF, PT , PQSAT , KFLAG)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KTDIA
LOGICAL ,INTENT(IN) :: LDPHYLIN
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRSF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQSAT(KLON,KLEV)
INTEGER(KIND=JPIM),INTENT(IN) :: KFLAG
END SUBROUTINE SATUR_CPU
end interface