INTERFACE
SUBROUTINE SRTM_CMBGB22_GPU(lacc)
logical, intent (in) :: lacc
END SUBROUTINE SRTM_CMBGB22_GPU
END INTERFACE
INTERFACE
SUBROUTINE SRTM_CMBGB22_CPU
END SUBROUTINE SRTM_CMBGB22_CPU
END INTERFACE