INTERFACE
SUBROUTINE SRTM_CMBGB18_GPU(lacc)
logical, intent (in) :: lacc
END SUBROUTINE SRTM_CMBGB18_GPU
END INTERFACE
INTERFACE
SUBROUTINE SRTM_CMBGB18_CPU
END SUBROUTINE SRTM_CMBGB18_CPU
END INTERFACE