INTERFACE
SUBROUTINE SRTM_CMBGB25_GPU(lacc)
logical, intent (in) :: lacc
END SUBROUTINE SRTM_CMBGB25_GPU
END INTERFACE
INTERFACE
SUBROUTINE SRTM_CMBGB25_CPU
END SUBROUTINE SRTM_CMBGB25_CPU
END INTERFACE