INTERFACE
SUBROUTINE SRTM_CMBGB23_GPU(lacc)
logical, intent (in) :: lacc
END SUBROUTINE SRTM_CMBGB23_GPU
END INTERFACE
INTERFACE
SUBROUTINE SRTM_CMBGB23_CPU
END SUBROUTINE SRTM_CMBGB23_CPU
END INTERFACE