INTERFACE
SUBROUTINE SRTM_CMBGB17_GPU(lacc)
logical, intent (in) :: lacc
END SUBROUTINE SRTM_CMBGB17_GPU
END INTERFACE
INTERFACE
SUBROUTINE SRTM_CMBGB17_CPU
END SUBROUTINE SRTM_CMBGB17_CPU
END INTERFACE