INTERFACE
SUBROUTINE SRTM_CMBGB24_GPU(lacc)
logical, intent (in) :: lacc
END SUBROUTINE SRTM_CMBGB24_GPU
END INTERFACE
INTERFACE
SUBROUTINE SRTM_CMBGB24_CPU
END SUBROUTINE SRTM_CMBGB24_CPU
END INTERFACE