INTERFACE
SUBROUTINE SRTM_CMBGB27_GPU(lacc)
logical, intent (in) :: lacc
END SUBROUTINE SRTM_CMBGB27_GPU
END INTERFACE
INTERFACE
SUBROUTINE SRTM_CMBGB27_CPU
END SUBROUTINE SRTM_CMBGB27_CPU
END INTERFACE