INTERFACE
SUBROUTINE SRTM_CMBGB29_GPU(lacc)
logical, intent (in) :: lacc
END SUBROUTINE SRTM_CMBGB29_GPU
END INTERFACE
INTERFACE
SUBROUTINE SRTM_CMBGB29_CPU
END SUBROUTINE SRTM_CMBGB29_CPU
END INTERFACE