INTERFACE
SUBROUTINE SRTM_CMBGB26_GPU(lacc)
logical, intent (in) :: lacc
END SUBROUTINE SRTM_CMBGB26_GPU
END INTERFACE
INTERFACE
SUBROUTINE SRTM_CMBGB26_CPU
END SUBROUTINE SRTM_CMBGB26_CPU
END INTERFACE