INTERFACE
SUBROUTINE SRTM_CMBGB20_GPU(lacc)
logical, intent (in) :: lacc
END SUBROUTINE SRTM_CMBGB20_GPU
END INTERFACE
INTERFACE
SUBROUTINE SRTM_CMBGB20_CPU
END SUBROUTINE SRTM_CMBGB20_CPU
END INTERFACE