INTERFACE
SUBROUTINE SRTM_CMBGB19_GPU(lacc)
logical, intent (in) :: lacc
END SUBROUTINE SRTM_CMBGB19_GPU
END INTERFACE
INTERFACE
SUBROUTINE SRTM_CMBGB19_CPU
END SUBROUTINE SRTM_CMBGB19_CPU
END INTERFACE