INTERFACE
SUBROUTINE SRTM_CMBGB28_GPU(lacc)
logical, intent (in) :: lacc
END SUBROUTINE SRTM_CMBGB28_GPU
END INTERFACE
INTERFACE
SUBROUTINE SRTM_CMBGB28_CPU
END SUBROUTINE SRTM_CMBGB28_CPU
END INTERFACE