INTERFACE
SUBROUTINE SRTM_CMBGB16_GPU(lacc)
logical, intent (in) :: lacc
END SUBROUTINE SRTM_CMBGB16_GPU
END INTERFACE
INTERFACE
SUBROUTINE SRTM_CMBGB16_CPU
END SUBROUTINE SRTM_CMBGB16_CPU
END INTERFACE