INTERFACE
SUBROUTINE SRTM_INIT_GPU(DIRECTORY, NWVCONTINUUM, lacc)
USE PARKIND1, ONLY : JPIM
CHARACTER(LEN=*), INTENT(IN) :: DIRECTORY
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: NWVCONTINUUM
logical, intent (in) :: lacc
END SUBROUTINE SRTM_INIT_GPU
END INTERFACE
INTERFACE
SUBROUTINE SRTM_INIT_CPU(DIRECTORY, NWVCONTINUUM)
USE PARKIND1, ONLY : JPIM
CHARACTER(LEN=*), INTENT(IN) :: DIRECTORY
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: NWVCONTINUUM
END SUBROUTINE SRTM_INIT_CPU
END INTERFACE