INTERFACE
SUBROUTINE SRTM_CMBGB21_GPU(lacc)
logical, intent (in) :: lacc
END SUBROUTINE SRTM_CMBGB21_GPU
END INTERFACE
INTERFACE
SUBROUTINE SRTM_CMBGB21_CPU
END SUBROUTINE SRTM_CMBGB21_CPU
END INTERFACE